### ISSUE TITLE
Bug on simulation of sample of n=4000

### ISSUE THREAD

**Issue by MainaJohnO** [africanmathsinitiative/R-Instat-Help#13]
![capture_prepare menu_random numbergeneration](https://user-images.githubusercontent.com/32262789/33361660-29c232fc-d4ea-11e7-82fe-7f402a7db52e.PNG)

In regard to the eSMS assignments for R-instant during the review of topic 3 - Assignment1, under section(2.1) question 3 on simulation of samples when I try generating a sample of n=4000, the attached bug pops up. Indication that the Rice_Yield_Population data sets we are using is not up to date. May be an update of the Rice_Yield_Population data sets is required

**Comment by dannyparsons** [comment]
This is an issue with the connection to R, probably something went wrong in the simulation. 
Can you post the full log code that gave this error? 
Does it happen for any sample size you use? Does it only happen after doing a sequence of other things or does it always happen even if doing the simulation is the first thing you do?

**Comment by dannyparsons** [comment]
Also, it is better to report bugs with R-Instat on the [R-Instat repository](https://github.com/africanmathsinitiative/R-Instat/issues) and not the R-Instat Help repository.

**Comment by MainaJohnO** [comment]
The bug happens on sample sizes greater than 1000. For n=1000 the
simulation happens very well but for n=1001  the bug pops up hence for
n>1000 no sample simulation can be generated.

**Comment by dannyparsons** [comment]
Ok interesting to know that. @africanmathsinitiative/developers Is this the same limit on your machines?

**Comment by dannyparsons** [comment]
Closing this as duplicated in https://github.com/africanmathsinitiative/R-Instat/issues/4276
